# Generated by Django 5.1.2 on 2025-04-09 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studybuzz', '0003_room_participants'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-updated', '-created']},
        ),
    ]
