# Generated by Django 5.1.2 on 2025-04-09 06:51

import studybuzz.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studybuzz', '0004_alter_message_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=studybuzz.models.user_avatar_path),
        ),
    ]
